name: mandarinapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.3
  audioplayers: ^6.5.1
  font_awesome_flutter: ^10.12.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/audio/
    - assets/languages/

